language: python
python:
  - "2.7.13"

addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

# command to install dependencies
install: 
  - sudo apt-get update
  - sudo apt-get install libwebkitgtk-dev libjpeg-dev libtiff-dev libgtk2.0-dev libsdl1.2-dev freeglut3 freeglut3-dev libnotify-dev
  - echo "SIX_INSTALLATION"
  - travis_wait 60 sudo pip install -Uv six
  - echo "WXPYTHON_INSTALLATION"
  - wget "https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-14.04/wxPython-4.0.0a3.dev3059+4a5c5d9-cp35-cp35m-linux_x86_64.whl"
  - sudo pip install wxPython-4.0.0a3.dev3059+4a5c5d9-cp35-cp35m-linux_x86_64.whl 
 #travis_wait 60 sudo pip install -Uv wxpython
  - echo "WXPYTHON_INSTALLATION_FINISHED"
  - "pip install requests coveralls nose-htmloutput nose coverage"
  - echo "INSTALLATION_FINISHED"
  - python -V
script: nosetests -v --with-id  --with-coverage --with-html --cover-package=./

after_success:  
  - coveralls 
