language: python
python:
  - "3.5.3"

addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

# command to install dependencies
install: 
  - cat /etc/issue
  - sudo apt-get update
  - echo "SIX_INSTALLATION"
  #- travis_wait 60 sudo pip install -Uv six
  - echo "WXPYTHON_INSTALLATION"
  - wget "https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-14.04/wxPython-4.0.0a2.dev3038+953a2e5-cp35-cp35m-linux_x86_64.whl"
  - pip install wxPython-4.0.0a2.dev3038+953a2e5-cp35-cp35m-linux_x86_64.whl 
 #travis_wait 60 sudo pip install -Uv wxpython
  - echo "WXPYTHON_INSTALLATION_FINISHED"
  - "pip install requests coveralls nose-htmloutput nose coverage"
  - echo "INSTALLATION_FINISHED"
  - python -V
script: nosetests -v --with-id  --with-coverage --with-html --cover-package=./

after_success:  
  - coveralls 
