anguage: python
python:
  - "3.6.2"

addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

# command to install dependencies
install: 
  - sudo apt-get update
  - sudo apt-get install libwebkitgtk-dev libjpeg-dev libtiff-dev libgtk2.0-dev libsdl1.2-dev freeglut3 freeglut3-dev libnotify-dev
  - echo "WXPYTHON_INSTALLATION"
  - travis_wait 30 sudo pip install -Uv wxpython
  - echo "WXPYTHON_INSTALLATION_FINISHED"
  - "pip install requests coveralls nose-htmloutput nose coverage"
  - echo "INSTALLATION_FINISHED"
script: nosetests -v --with-id  --with-coverage --with-html --cover-package=./

after_success:  
  - coveralls 
